language: node_js
node_js:
  - "0.10"
before_script:
  - npm install -g gulp
  - npm install -g bower
  - bower install
env:
  global:
    - secure: EatnSoK1vMKvuxXYuPomO4nfk1IRAHK2Ai88NhTvm+y6U5m22Xeo6ROVN5SwnMqiiHRpkqXJKiBrRUldyNX8iemt1HhkjLcoUnAvqHYescYzt/2re32KtWVuCq5pBYFfE+zDJzDPC+XpHSkfINO95vec4BQc/fZ1cqhiM76OhKc=
    - secure: LvznPzWRU8hAY6j/oMT6CxHdR6yZqiqaw6hjPILFZLJSrYi11DWV6oE45zmZy1ErW6O0N7iNp89kKLCkJJS27lrb5oynkWLBGpthFTv71JGrmyVfArLjg+RZo33I4Rvcsp4aCUys8e3m0yuIOGQg430k6yInbXyNppUG6FJClDw=